version: '2'
services:
    springangularsampleapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/springAngularSampleApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=springAngularSampleApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
